"""Schemas del Nicho POV BOF."""

from .models import (
    BackupCheckResponse,
    BackupSyncRequest,
    BackupSyncResponse,
    ExtraerTextosRequest,
    FoldersListResponse,
    MarkCompletedRequest,
    MarkCompletedResponse,
    PhotoInfo,
    PhotosListResponse,
    ProductFolder,
    ProductoEstadoRequest,
    ProductoInfo,
    ProductosListResponse,
    ProductosUrlsRequest,
    ProductosUrlsResponse,
    ProductoUrlRequest,
    PromptsResponse,
    SoldProductsResponse,
    SourceInfo,
    SourcesListResponse,
    VideoUploadResponse,
)

__all__ = [
    "BackupCheckResponse",
    "BackupSyncRequest",
    "BackupSyncResponse",
    "ExtraerTextosRequest",
    "FoldersListResponse",
    "MarkCompletedRequest",
    "MarkCompletedResponse",
    "PhotoInfo",
    "PhotosListResponse",
    "ProductFolder",
    "ProductoEstadoRequest",
    "ProductoInfo",
    "ProductosListResponse",
    "ProductosUrlsRequest",
    "ProductosUrlsResponse",
    "ProductoUrlRequest",
    "PromptsResponse",
    "SoldProductsResponse",
    "SourceInfo",
    "SourcesListResponse",
    "VideoUploadResponse",
]
